### ISSUE TITLE
Needed libraries on Ubuntu 22.04

### ISSUE THREAD

**Issue by merces** [mentebinaria/elfparser-ng#8]
I had to install both FUSE and qtbase5-dev before running the AppImage on Linux (Ubuntu 22.04 64-bits). Fixed with:

    sudo apt install fuse qtbase5-dev

Is this expected?

After installing both and trying to execute the AppImage binary, it says `libicudata.so.71` is missing. It also complains about `libicui18n.so.71`, and `libicuuc.so.71`. Here's how I fixed it:

    ln -s /usr/lib/x86_64-linux-gnu/libicudata.so.70.1 /usr/lib/x86_64-linux-gnu/libicudata.so.71
    ln -s /usr/lib/x86_64-linux-gnu/libicui18n.so.70.1 /usr/lib/x86_64-linux-gnu/libicui18n.so.71
    ln -s /usr/lib/x86_64-linux-gnu/libicuuc.so.70.1 /usr/lib/x86_64-linux-gnu/libicuuc.so.71

Then it runs.

**Comment by rem0obb** [comment]
Yes, it's necessary
